title: Blog de Benjamin Camacho
email: jahbenjah@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  El blog de Benjamin Camacho esta dedicado a temas de desarrollo de software.
  C#,Pruebas Unitarias, Test Driven Development,.NET ,.NET Core, docker , Linux ,SQL
  
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://jahbenjah.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jbenjamincmcho
github_username:  jahbenjah

# Build settings
markdown: kramdown
theme: jekyll-theme-tactile
plugins:
  - jekyll-feed
