lang: es
title: ASP.NET Core Master
author: Benjamin Camacho
email: benjamin@aspnetcoremaster.com
description: >-
  Sitio dedicado a temas de programación usando C# ,ASP.NET Core, Entity Framework Core y Sql Server.
baseurl: ""
url: "https://aspnetcoremaster.com"
twitter_username: jbenjamincc
github_username:  jahbenjah
linkedin_username: benjamin-camacho-castro
youtube_channel_name: Benjamín Camacho
youtube_channel: UCFz5TO8oRcws22p96jrBeqQ
twitter:
  username: jbenjamincc
  card: summary
  image: /img/og-image.webp
social:
  name: aspnetcoremaster
  links:
    - https://www.facebook.com/aspnetcoremaster/
markdown: kramdown
theme: minima
show_excerpts: false

disqus:
 shortname: https-jahbenjah-github-io

google_analytics: UA-130293099-1

header_pages:
 - libros.md
 - software.md
 - computadoras.md
 
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

collections:
  authors:
    output: true
  plantillas:
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      lang: "es"
      lazy: true
      image:
        path: /img/og-image.webp
        height: 347
        width: 663
      author: benjamin
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"