lang: es
title: ASP.NET Core Master
author: Benjamin Camacho
email: j.benjamin.camacho@gmail.com
description: >-
  En este sitio encontrarás artículos sobre programación usando C# ,ASP.NET Core y Entity Framework Core .
baseurl: ""
url: "https://www.aspnetcoremaster.com"
twitter_username: jbenjamincmcho
github_username:  jahbenjah
linkedin_username: benjamin-camacho-castro
twitter:
  username: jbenjamincmcho
  card: summary
logo: /og-image.jpg
social:
  name: csharpmx
  links:
    - https://www.facebook.com/csharpmx/
markdown: kramdown
theme: minima
show_excerpts: true

disqus:
 shortname: https-jahbenjah-github-io

google_analytics: UA-130293099-1

header_pages:
 - contacto.md

defaults:
  -
    scope:
      path: ""
    values:
      lang: "es"
      image:
        path: /og-image.jpg
        height: 347
        width: 663

toc:
  min_level:        2
  max_level:        4
  no_toc_section_class:
    - "bd-callout"
    - "bd-example"