# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
# Site Settings
locale                   : "es_MX"
# End Site Settings
title: Programación con C#
email: j.benjamin.camacho@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  En este sitio encontraras articiulos sobre programación usando C# .
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jahbenjah.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jbenjamincmcho
github_username:  jahbenjah
linkedin_username: jbenjamin-camacho-castro
# youtube_username: jahbenjah

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-mentions
  - jekyll-seo-tag

show_excerpts: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

disqus:
    shortname: benjamincamachoblog
    

header_pages:
 acerca.md
 portafolio.md
 contacto.md